// src/components/ProductPage/productsData.js
export const categories = [
  { id: 'all', name: 'All Products' },
  { id: 'makeup', name: 'Makeup' },
  { id: 'skincare', name: 'Skincare' },
  { id: 'haircare', name: 'Hair Care' },
  { id: 'fragrance', name: 'Fragrance' },
  // { id: 'tools', name: 'Tools & Brushes' },
];

export const products = [
  {
    id: 1,
    name: 'Dior Lip Glow',
    category: 'makeup',
    price: 38,
    image: 'https://via.placeholder.com/300x300/ff6b9d/fff?text=Dior+Lip+Glow',
    description: 'Iconic tinted lip balm that reacts with your lips\' pH to create a custom pink glow. Infused with mango butter for 24h hydration.',
  },
  {
    id: 2,
    name: 'Fenty Beauty Gloss Bomb',
    category: 'makeup',
    price: 26,
    image: 'https://via.placeholder.com/300x300/ff9ff3/000?text=Fenty+Gloss',
    description: 'Explosive shine that makes lips look instantly fuller. Non-sticky formula with shea butter and a peach-vanilla scent.',
  },
  {
    id: 3,
    name: 'La Mer Crème de la Mer',
    category: 'skincare',
    price: 380,
    image: 'https://via.placeholder.com/300x300/4ecdc4/fff?text=La+Mer',
    description: 'The legendary moisturizer with Miracle Broth™. Delivers deep hydration, soothes sensitivity, and promotes a radiant glow.',
  },
  {
    id: 4,
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    category: 'skincare',
    price: 8,
    image: 'https://via.placeholder.com/300x300/95e1d3/000?text=The+Ordinary',
    description: 'High-strength vitamin and mineral formula that reduces blemishes, minimizes pores, and balances oil production.',
  },
  {
    id: 5,
    name: 'Olaplex No.3 Hair Perfector',
    category: 'haircare',
    price: 30,
    image: 'https://via.placeholder.com/300x300/f7c6c7/000?text=Olaplex',
    description: 'At-home bond-building treatment that repairs damaged hair from within. Dramatically reduces breakage and strengthens hair.',
  },
  {
    id: 6,
    name: 'Chanel No.5 Eau de Parfum',
    category: 'fragrance',
    price: 135,
    image: 'https://via.placeholder.com/300x300/f9ca24/000?text=Chanel+N°5',
    description: 'The ultimate feminine fragrance since 1921. Timeless blend of rose, jasmine, ylang-ylang, and warm vanilla base notes.',
  },
  {
    id: 6,
    name: 'Chanel No.5 Eau de Parfum',
    category: 'fragrance',
    price: 135,
    image: 'https://via.placeholder.com/300x300/f9ca24/000?text=Chanel+N°5',
    description: 'The ultimate feminine fragrance since 1921. Timeless blend of rose, jasmine, ylang-ylang, and warm vanilla base notes.',
  },
  {
    id: 6,
    name: 'Chanel No.5 Eau de Parfum',
    category: 'fragrance',
    price: 135,
    image: 'https://via.placeholder.com/300x300/f9ca24/000?text=Chanel+N°5',
    description: 'The ultimate feminine fragrance since 1921. Timeless blend of rose, jasmine, ylang-ylang, and warm vanilla base notes.',
  },
  {
    id: 6,
    name: 'Chanel No.5 Eau de Parfum',
    category: 'fragrance',
    price: 135,
    image: 'https://via.placeholder.com/300x300/f9ca24/000?text=Chanel+N°5',
    description: 'The ultimate feminine fragrance since 1921. Timeless blend of rose, jasmine, ylang-ylang, and warm vanilla base notes.',
  },
];